export const competitionTemplates = [
  {
    label: "Football League 2025",
    data: {
      name: "Football League 2025",
      sport: "Football",
      venue: "National Stadium",
      maxTeams: 16,
      startDate: new Date("2025-07-01"),
      endDate: new Date("2025-08-01"),
      registrationDeadline: new Date("2025-06-15"),
      description: "Annual national football league featuring top teams from across the country. Matches will be played in a round-robin format followed by knockout stages.",
      rules: "1. Standard FIFA rules apply\n2. Each match is 90 minutes\n3. Points: Win=3, Draw=1, Loss=0",
      prizes: "1st Place: Trophy + $5000\n2nd Place: $3000\n3rd Place: $1000",
    },
  },
  {
    label: "Intercollege Basketball Cup",
    data: {
      name: "Intercollege Basketball Cup",
      sport: "Basketball",
      venue: "City Sports Arena",
      maxTeams: 8,
      startDate: new Date("2025-09-05"),
      endDate: new Date("2025-09-20"),
      registrationDeadline: new Date("2025-08-25"),
      description: "A high-energy intercollege basketball tournament bringing together the best college teams. Features group stages and knockout rounds.",
      rules: "1. FIBA rules apply\n2. 4 quarters of 10 minutes each\n3. Teams must be registered with their college",
      prizes: "1st Place: Championship Trophy + Medals\n2nd Place: Silver Medals\n3rd Place: Bronze Medals",
    },
  },
  {
    label: "Cricket T20 Fest",
    data: {
      name: "Cricket T20 Fest",
      sport: "Cricket",
      venue: "Central Cricket Ground",
      maxTeams: 12,
      startDate: new Date("2025-10-10"),
      endDate: new Date("2025-10-30"),
      registrationDeadline: new Date("2025-09-25"),
      description: "Fast-paced T20 cricket tournament with the best teams competing for glory. Features league matches followed by playoffs.",
      rules: "1. ICC T20 rules apply\n2. 20 overs per innings\n3. Power play in first 6 overs",
      prizes: "1st Place: Trophy + Prize Money\n2nd Place: Runner-up Trophy\n3rd Place: Consolation Prize",
    },
  },
  {
    label: "College Athletics Meet",
    data: {
      name: "College Athletics Meet",
      sport: "Athletics",
      venue: "University Sports Complex",
      maxTeams: 10,
      startDate: new Date("2025-11-15"),
      endDate: new Date("2025-11-17"),
      registrationDeadline: new Date("2025-10-31"),
      description: "Comprehensive track and field event featuring multiple athletic disciplines. Open to all college athletes.",
      rules: "1. World Athletics rules apply\n2. Athletes can participate in max 3 events\n3. Heats followed by finals",
      prizes: "Gold, Silver, and Bronze medals for each event",
    },
  },
  {
    label: "Badminton Blitz",
    data: {
      name: "Badminton Blitz",
      sport: "Badminton",
      venue: "Indoor Sports Hall",
      maxTeams: 6,
      startDate: new Date("2025-06-01"),
      endDate: new Date("2025-06-03"),
      registrationDeadline: new Date("2025-05-20"),
      description: "Fast-paced badminton tournament.",
      rules: "1. Matches are best of 3 games\n2. Each game to 21 points\n3. Standard BWF rules apply",
      prizes: "1st: Trophy + Gifts\n2nd: Runner-up Trophy\n3rd: Consolation Prize",
    },
  },
  {
    label: "Esports Showdown",
    data: {
      name: "Esports Showdown",
      sport: "Esports",
      venue: "Tech Arena",
      maxTeams: 20,
      startDate: new Date("2025-07-15"),
      endDate: new Date("2025-07-20"),
      registrationDeadline: new Date("2025-07-01"),
      description: "Competitive gaming tournament across various titles.",
      rules: "1. Standard game-specific rules apply\n2. Double elimination format\n3. Fair play mandatory",
      prizes: "1st: $2000 + Trophy\n2nd: $1000\n3rd: $500",
    },
  },
  {
    label: "Volleyball Cup",
    data: {
      name: "Volleyball Cup",
      sport: "Volleyball",
      venue: "Beach Sports Park",
      maxTeams: 10,
      startDate: new Date("2025-08-10"),
      endDate: new Date("2025-08-14"),
      registrationDeadline: new Date("2025-07-30"),
      description: "Outdoor beach volleyball tournament.",
      rules: "1. FIVB beach volleyball rules apply\n2. Matches best of 3 sets\n3. Team uniforms required",
      prizes: "1st: Trophy + Medals\n2nd: Medals\n3rd: Certificates",
    },
  },
  {
    label: "Chess Masters",
    data: {
      name: "Chess Masters",
      sport: "Chess",
      venue: "Library Hall",
      maxTeams: 32,
      startDate: new Date("2025-09-01"),
      endDate: new Date("2025-09-05"),
      registrationDeadline: new Date("2025-08-20"),
      description: "Tournament for master-level chess players.",
      rules: "1. FIDE rules apply\n2. 90 minutes per player per game\n3. Tie-breakers as per Buchholz system",
      prizes: "1st: Trophy + Cash Prize\n2nd: Cash Prize\n3rd: Certificate of Excellence",
    },
  },
];
